### ISSUE TITLE
Nested calc are not resolved when coupled with rework-vars & some differents unit.

### ISSUE THREAD

**Issue by MoOx** [reworkcss/rework-calc#5]
``` css
:root {
  --fontSizeUnit: 1rem;
  --fontSizeRatio: 0.75;
  --fontSize: calc(var(--fontSizeUnit) * var(--fontSizeRatio));
  --lineHeight: calc(var(--fontSize) * 1.5);

  --gutter-y: var(--lineHeight);
}

stuff {
  debug: var(--lineHeight);
  debug2: var(--gutter-y);
  debug3: calc(var(--gutter-y) * 1);
  debug3: calc(var(--gutter-y) - 1rem);
  debug4: calc(var(--gutter-y) - 1px);
}
```

give

``` css
stuff {
  debug: 1.125rem;
  debug2: 1.125rem;
  debug3: 1.125rem;
  debug3: 0.125rem;
  debug4: calc(calc(calc(1rem * 0.75) * 1.5) - 1px);
}
```

expected (should be the same in the browser rendering ?)

``` css
stuff {
  debug: 1.125rem;
  debug2: 1.125rem;
  debug3: 1.125rem;
  debug3: 0.125rem;
  debug4: calc(1.125rem - 1px);
}
```

I need to fix that.
