### ISSUE TITLE
Calculations with unitless values

### ISSUE THREAD

**Issue by carlcs** [reworkcss/rework-calc#7]
Currently it's not possible to calculate unitless values. Using percentages or ems is no alternative with `line-height` for example, if you'd like the child elements to inherit that unitless value, rather than the computed value of the parent.

``` css
:root {
  --font-size-ratio: 14;
  --line-height-ratio: 22;
  --line-height: calc( var(--line-height-ratio) / var(--font-size-ratio) );
}

html {
  line-height: var(--line-height);
}
```

Output is in units px:

``` css
html {
  line-height: 1.57142857142857px;
}
```
