### ISSUE TITLE
Calculations to convert units

### ISSUE THREAD

**Issue by carlcs** [reworkcss/rework-calc#8]
Is there really no way to do unit conversions other than having unitless "ratio" values to begin with? Why does `calc( 4em / 1em )` result in `4em` and not `4`?

This is what I'd like to do:

``` css
:root {
  --font-size-em: 1em;
  --font-size-px: 16px;
}

:root {
  --space-large-em: 4em;
  --space-large-px: calc( ( var(--space-large-em) / var (--font-size-em) ) * var(--font-size-px) );
}

.grid-cell {
  padding: 0 calc( var(--space-large-px) / 2 );
}

.article-header {
  margin-bottom: var(--space-large-em);
}
```

Expected result:

``` css
.grid-cell {
  padding: 0 32px;
}

.article-header {
  margin-bottom: 4em;
}
```

**Comment by MoOx** [comment]
`calc( 4em / 1em )` is just invalid CSS (firefox, safari & chrome confirm that)

I think this should throw an exception when you try to \* or / same unit.

**Comment by carlcs** [comment]
Yep, this is from the [MDN Article](https://developer.mozilla.org/en-US/docs/Web/CSS/calc):

> Multiplication. At least one of the arguments must be a <number>.
> Division. The right-hand side must be a <number>.

So this means, we have to use unitless values for such calculations or use a preprocessor for it.

**Comment by MoOx** [comment]
Yep but... it's a bug, you shouldn't get 4em as a result. It should be left as it his (+ eventually a warning)

**Comment by carlcs** [comment]
@MoOx I actually don't see the reason to forbid divisions where the divisor is of the same unit as the dividend is. Do you know where such decisions are made?

**Comment by MoOx** [comment]
Here you will see that there is a removal of the unit, if only one has been spotted.
https://github.com/reworkcss/rework-calc/blob/2663985cc3d824cc8facdd4b0695927d01df59ba/index.js#L119-L133
So this will be a bit complicated fix this issue.

**Comment by carlcs** [comment]
I totally understand that one should prevent things like:

``` css
body {
  font-size: calc( 10px * 10px );
  font-size: calc( 10px / 2rem );
}
```

But I would really appreciate if this would be within the CSS specs:

``` css
body {
  line-height: calc( 24px / 16px );
}
```

**Comment by carlcs** [comment]
> Do you know where such decisions are made?

I meant where the CSS specs decisions are made. Can't find `calc()` proposal or discussions thread anywhere.

**Comment by MoOx** [comment]
No idea where.
As a simple workaround, you should be able to do this

``` css
:root {
  --font-size-em: 1;
  --font-size-px: 16;
}

:root {
  --space-large-em: calc(4 * 1em);
  --space-large-px: calc( ( var(--space-large-em) / var (--font-size-em) ) * var(--font-size-px) * 1px);
}

.grid-cell {
  padding: 0 calc( var(--space-large-px) / 2 );
}

.article-header {
  margin-bottom: var(--space-large-em);
}
```

**Comment by carlcs** [comment]
Just found this:

> I brought up the question of being able to divide two <length>s in
> calc() earlier this week, [...]
> 1. If both sides have the same type, resolve to <number>.

Source: http://lists.w3.org/Archives/Public/www-style/2014Apr/0101.html

**Comment by carlcs** [comment]
After reading through some of these W3C mailing lists, it seems like there's indeed more math coming to CSS `calc()`:

> Tab Atkins Jr.: [...] today we accepted this proposal for V&U Level 4 [...]

Source: http://lists.w3.org/Archives/Public/www-style/2014Apr/0358.html

**Comment by carlcs** [comment]
Does it make sense to already implement some of these new features in rework-calc? My current workaround is pretty similar to what @MoOx suggested, but I think something like this is far from ideal:

``` css
:root {
  --font-size-base-dimensionless: 16;
  --font-size-base-em: calc( var(--font-size-base-dimensionless) / 16 * 1em );
  --font-size-base-px: calc( var(--font-size-base-dimensionless) * 1px );
}
```

If we could have this:

``` css
:root {
  --font-size-base-em: 1em;
  --font-size-base-px: calc( var(--font-size-base-em) / 1em * 16px );
}
```
